source 'http://rubygems.org'

gem 'rails', '3.2'
gem 'sqlite3', '~> 1.3.8'

gem 'best_in_place', '~> 2.1.0'

gem "jquery-rails", "~> 3.0.4"
gem "jquery-ui-rails", "~> 4.0.3"

gem 'rdiscount', '~> 2.1.6'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
